version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/requirements.txt
  extra_requirements:
    - docs

conda:
  environment: environment.yml

sphinx:
  configuration: docs/conf.py
