# environment.yml
name: matilda_edu_mat
channels:
- conda-forge
- plotly
dependencies:
- python==3.10.9
- geemap==0.19.6
- pysheds==0.3.3
- geopandas==0.12.2
- xarray==2023.2.0
- netcdf4==1.6.0
- retry==0.9.2
- utm==0.7.0
- bias_correction==0.4
- fastparquet==2023.4.0
- dash==2.9.3
- jupyter-dash==0.4.2
- seaborn==0.12.2
- spotpy==1.6.2
- mpl-probscale==0.2.5
- jupyter-dash==0.4.2
- h5netcdf==1.2.0
- pip
- pip:
  - git+https://github.com/cryotools/matilda.git
  - climate-indices==1.0.13
