# environment.yml
name: matilda_edu_mat
channels:
- conda-forge
dependencies:
- python==3.10.9
- geemap==0.19.6
- pysheds==0.3.3
- geopandas==0.12.2
- xarray==2023.2.0
- netcdf4==1.6.0
- pip
- pip:
  - git+https://github.com/cryotools/matilda.git/#egg=matilda&subdirectory=matilda_v0.3
