# environment.yml
name: matilda_edu_mat
channels:
- conda-forge
dependencies:
- python==3.12
- numpy==1.26.4
- geemap==0.35
- pysheds==0.4
- hydroerr==1.24
- geopandas==1.0.1
- xarray==2024.10.0
- h5netcdf==1.4
- retry==0.9.2
- utm==0.7.0
- bias_correction==0.4
- fastparquet==2024.5.0
- dash==2.18.1
- jupytext==1.16.4
- nodejs-22.9.0
- seaborn==0.13.2
- Fiona==1.10.1
- spotpy==1.6.2
- mpl-probscale==0.2.5
- pip:
  - git+https://github.com/cryotools/matilda.git
  - climate_indices==1.0.12
  - hydroeval==0.1.0